/*
 * generated by Xtext 2.29.0
 */
package org.itlingo.asl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.itlingo.asl.AslRuntimeModule;
import org.itlingo.asl.AslStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class AslIdeSetup extends AslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new AslRuntimeModule(), new AslIdeModule()));
	}
	
}
