/*
 * generated by Xtext 2.29.0
 */
package org.itlingo.asl;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class AslRuntimeModule extends AbstractAslRuntimeModule {
}
