/*
 * generated by Xtext 2.29.0
 */
package org.itlingo.asl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class AslStandaloneSetup extends AslStandaloneSetupGenerated {

	public static void doSetup() {
		new AslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
